import type {
  CreateProjectRequest,
  Env,
  GitHubRepository,
  MobilePlatform,
  MobilePreset
} from "./types";

const GITHUB_API = "https://api.github.com";
const GITHUB_API_VERSION = "2022-11-28";
const BLUEPRINT_VERSION = 1;

class GitHubMobileApiError extends Error {
  constructor(readonly status: number, readonly path: string, detail: string) {
    super(`GitHub API ${status} on ${path}: ${detail}`);
  }
}

interface GitTreeEntry {
  path: string;
  mode: string;
  type: string;
  sha: string;
}

interface MobileMarker {
  schemaVersion: number;
  projectType: "mobile";
  platform: MobilePlatform;
  preset: MobilePreset;
  blueprintVersion: number;
}

async function githubRequest<T>(token: string, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": GITHUB_API_VERSION,
      "User-Agent": "Trigenys-AppFactory",
      ...(init.headers || {})
    }
  });

  if (!response.ok) {
    throw new GitHubMobileApiError(response.status, path, await response.text());
  }

  return (await response.json()) as T;
}

function decodeBase64(value: string): string {
  const binary = atob(value.replace(/\s+/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return new TextDecoder().decode(bytes);
}

function encodeBase64(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

async function fetchRepository(token: string, owner: string, slug: string): Promise<GitHubRepository | null> {
  try {
    return await githubRequest<GitHubRepository>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(slug)}`
    );
  } catch (error) {
    if (error instanceof GitHubMobileApiError && error.status === 404) return null;
    throw error;
  }
}

async function createRepository(
  token: string,
  owner: string,
  input: CreateProjectRequest & { slug: string }
): Promise<GitHubRepository> {
  return githubRequest<GitHubRepository>(token, `/orgs/${encodeURIComponent(owner)}/repos`, {
    method: "POST",
    body: JSON.stringify({
      name: input.slug,
      description: input.description || `Generated by AppFactory for ${input.name}`,
      private: input.private ?? true,
      auto_init: true,
      has_issues: true,
      has_projects: true,
      has_wiki: false
    })
  });
}

async function readJsonFile<T>(
  token: string,
  repository: GitHubRepository,
  path: string
): Promise<T | null> {
  const [owner, repo] = repository.full_name.split("/");
  try {
    const file = await githubRequest<{ content: string; encoding: string }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path}`
    );
    if (file.encoding !== "base64") throw new Error(`Unsupported GitHub content encoding for ${path}.`);
    return JSON.parse(decodeBase64(file.content)) as T;
  } catch (error) {
    if (error instanceof GitHubMobileApiError && error.status === 404) return null;
    throw error;
  }
}

async function writeProvisioningMarker(
  token: string,
  repository: GitHubRepository,
  platform: MobilePlatform,
  preset: MobilePreset
): Promise<void> {
  const [owner, repo] = repository.full_name.split("/");
  const path = ".appfactory/mobile-provisioning.json";
  const body = {
    schemaVersion: 1,
    projectType: "mobile",
    platform,
    preset,
    blueprintVersion: BLUEPRINT_VERSION,
    complete: false
  };

  await githubRequest(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message: "chore(appfactory): claim mobile provisioning",
        content: encodeBase64(`${JSON.stringify(body, null, 2)}\n`),
        branch: repository.default_branch || "main"
      })
    }
  );
}

async function getHeadSha(token: string, repository: GitHubRepository): Promise<string> {
  const [owner, repo] = repository.full_name.split("/");
  const ref = await githubRequest<{ object: { sha: string } }>(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/ref/heads/${encodeURIComponent(repository.default_branch || "main")}`
  );
  return ref.object.sha;
}

function packageSegment(slug: string): string {
  const normalized = slug.toLowerCase().replace(/[^a-z0-9]/g, "");
  if (!normalized) return "mobileapp";
  return /^[a-z]/.test(normalized) ? normalized : `app${normalized}`;
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function escapeJsonString(value: string): string {
  return JSON.stringify(value).slice(1, -1);
}

function renderBlueprintText(
  content: string,
  context: { owner: string; name: string; slug: string }
): string {
  return content
    .replaceAll("__OWNER__", context.owner)
    .replaceAll("__APP_NAME_XML__", escapeXml(context.name))
    .replaceAll("__APP_NAME_JSON__", escapeJsonString(context.name))
    .replaceAll("__APP_NAME__", context.name)
    .replaceAll("__APP_SLUG__", context.slug)
    .replaceAll("appfactoryplaceholder", packageSegment(context.slug));
}

async function materializeBlueprint(
  token: string,
  env: Env,
  repository: GitHubRepository,
  preset: MobilePreset,
  appName: string
): Promise<string> {
  const targetOwner = env.GITHUB_OWNER || "Trigenys";
  const sourceOwner = env.GITHUB_MOBILE_BLUEPRINT_OWNER || targetOwner;
  const sourceRepo = env.GITHUB_MOBILE_BLUEPRINT_REPO || "appfactory";
  const source = await githubRequest<GitHubRepository>(
    token,
    `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}`
  );
  const sourceRef = env.GITHUB_MOBILE_BLUEPRINT_REF || source.default_branch || "main";
  const prefix = `blueprints/${preset}/`;
  const tree = await githubRequest<{ truncated: boolean; tree: GitTreeEntry[] }>(
    token,
    `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}/git/trees/${encodeURIComponent(sourceRef)}?recursive=1`
  );
  if (tree.truncated) throw new Error("AppFactory mobile blueprint tree is too large to materialize safely.");

  const sourceBlobs = tree.tree.filter((entry) => entry.type === "blob" && entry.path.startsWith(prefix));
  if (sourceBlobs.length === 0) throw new Error(`No files found for mobile blueprint ${preset}.`);

  const [, targetRepo] = repository.full_name.split("/");
  const targetEntries = await Promise.all(sourceBlobs.map(async (entry) => {
    const sourceBlob = await githubRequest<{ content: string; encoding: string }>(
      token,
      `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}/git/blobs/${entry.sha}`
    );
    if (sourceBlob.encoding !== "base64") throw new Error(`Unsupported blueprint encoding for ${entry.path}.`);

    const rendered = renderBlueprintText(decodeBase64(sourceBlob.content), {
      owner: targetOwner,
      name: appName,
      slug: repository.name
    });

    return {
      path: entry.path
        .slice(prefix.length)
        .replaceAll("appfactoryplaceholder", packageSegment(repository.name)),
      mode: entry.mode,
      type: "blob",
      content: rendered
    };
  }));

  const targetTree = await githubRequest<{ sha: string }>(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/trees`,
    { method: "POST", body: JSON.stringify({ tree: targetEntries }) }
  );
  const parentSha = await getHeadSha(token, repository);
  const commit = await githubRequest<{ sha: string }>(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/commits`,
    {
      method: "POST",
      body: JSON.stringify({
        message: `feat(appfactory): materialize ${preset} mobile blueprint`,
        tree: targetTree.sha,
        parents: [parentSha]
      })
    }
  );
  await githubRequest(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/refs/heads/${encodeURIComponent(repository.default_branch || "main")}`,
    { method: "PATCH", body: JSON.stringify({ sha: commit.sha, force: false }) }
  );
  return commit.sha;
}

function validMarker(
  marker: MobileMarker | null,
  platform: MobilePlatform,
  preset: MobilePreset
): boolean {
  return Boolean(
    marker &&
    marker.schemaVersion === 1 &&
    marker.projectType === "mobile" &&
    marker.platform === platform &&
    marker.preset === preset &&
    marker.blueprintVersion === BLUEPRINT_VERSION
  );
}

export async function provisionMobileRepository(
  token: string,
  env: Env,
  input: CreateProjectRequest & {
    slug: string;
    projectType: "mobile";
    platform: MobilePlatform;
    preset: MobilePreset;
  }
): Promise<{ repository: GitHubRepository; commitSha: string; replay: boolean }> {
  const owner = env.GITHUB_OWNER || "Trigenys";
  let repository = await fetchRepository(token, owner, input.slug);

  if (repository) {
    const marker = await readJsonFile<MobileMarker>(token, repository, ".appfactory/mobile.json");
    if (validMarker(marker, input.platform, input.preset)) {
      return { repository, commitSha: await getHeadSha(token, repository), replay: true };
    }

    const provisioning = await readJsonFile<MobileMarker & { complete?: boolean }>(
      token,
      repository,
      ".appfactory/mobile-provisioning.json"
    );
    if (
      !provisioning ||
      provisioning.platform !== input.platform ||
      provisioning.preset !== input.preset ||
      provisioning.complete !== false
    ) {
      throw new Error(
        `Repository ${repository.full_name} already exists and is not managed by the requested mobile preset.`
      );
    }
  } else {
    repository = await createRepository(token, owner, input);
    await writeProvisioningMarker(token, repository, input.platform, input.preset);
  }

  const commitSha = await materializeBlueprint(token, env, repository, input.preset, input.name);
  return { repository, commitSha, replay: false };
}
