import type { CreateProjectRequest, Env, GitHubRepository } from "./types";
import type { OpenPageSiteConfig } from "./engines/openpage";

const GITHUB_API = "https://api.github.com";
const GITHUB_API_VERSION = "2022-11-28";
const DEFAULT_COMMIT_AUTHOR_NAME = "EagleFox31";
const DEFAULT_COMMIT_AUTHOR_EMAIL = "86088743+EagleFox31@users.noreply.github.com";
const ENGINE_MARKER_PATH = "appfactory.engine.json";

class GitHubApiError extends Error {
  constructor(
    readonly status: number,
    readonly path: string,
    readonly detail: string
  ) {
    super(`GitHub API ${status} on ${path}: ${detail}`);
  }
}

async function githubRequest<T>(token: string, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": GITHUB_API_VERSION,
      "User-Agent": "Trigenys-AppFactory",
      ...(init.headers || {})
    }
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new GitHubApiError(response.status, path, detail);
  }

  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

function commitAuthor(env: Env): { name: string; email: string } {
  return {
    name: env.GITHUB_COMMIT_AUTHOR_NAME || DEFAULT_COMMIT_AUTHOR_NAME,
    email: env.GITHUB_COMMIT_AUTHOR_EMAIL || DEFAULT_COMMIT_AUTHOR_EMAIL
  };
}

function ownerFromEnv(env: Env): string {
  return env.GITHUB_OWNER || "Trigenys";
}

function defaultDescription(input: CreateProjectRequest & { slug: string }): string {
  return `Generated by AppFactory/OpenPage for ${input.name}`;
}

function engineMarker(input: CreateProjectRequest & { slug: string }) {
  return {
    schemaVersion: 1,
    engine: "openpage",
    engineRepository: "Trigenys/appfactory-openpage-engine",
    project: {
      name: input.name,
      slug: input.slug,
      language: input.language || "en"
    }
  };
}

function engineMarkerText(input: CreateProjectRequest & { slug: string }): string {
  return `${JSON.stringify(engineMarker(input), null, 2)}\n`;
}

function encodeBase64Utf8(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function encodeContentPath(path: string): string {
  return path
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
}

async function readEngineMarker(token: string, repository: GitHubRepository): Promise<string | null> {
  const [owner, repo] = repository.full_name.split("/");
  try {
    const file = await githubRequest<{ content?: string; encoding?: string }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${ENGINE_MARKER_PATH}`
    );
    if (file.encoding !== "base64" || !file.content) return null;
    return atob(file.content.replace(/\s+/g, ""));
  } catch (error) {
    if (error instanceof GitHubApiError && (error.status === 404 || error.status === 409)) return null;
    throw error;
  }
}

async function readRepositoryHead(
  token: string,
  repository: GitHubRepository
): Promise<{ commitSha: string; treeSha: string } | null> {
  const [owner, repo] = repository.full_name.split("/");
  const branch = repository.default_branch || "main";

  try {
    const ref = await githubRequest<{ object: { sha: string } }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/ref/heads/${encodeURIComponent(branch)}`
    );
    const commit = await githubRequest<{ tree: { sha: string } }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/commits/${encodeURIComponent(ref.object.sha)}`
    );
    return { commitSha: ref.object.sha, treeSha: commit.tree.sha };
  } catch (error) {
    if (error instanceof GitHubApiError && (error.status === 404 || error.status === 409)) return null;
    throw error;
  }
}

async function initializeOpenPageRepository(
  token: string,
  env: Env,
  repository: GitHubRepository,
  input: CreateProjectRequest & { slug: string }
): Promise<void> {
  const [owner, repo] = repository.full_name.split("/");
  await githubRequest<unknown>(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${ENGINE_MARKER_PATH}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message: "chore(appfactory): initialize OpenPage project",
        content: encodeBase64Utf8(engineMarkerText(input)),
        author: commitAuthor(env)
      })
    }
  );
}

async function getExistingOpenPageRepository(
  token: string,
  env: Env,
  owner: string,
  slug: string,
  input: CreateProjectRequest & { slug: string }
): Promise<GitHubRepository> {
  const repository = await githubRequest<GitHubRepository & { description?: string | null }>(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(slug)}`
  );
  const marker = await readEngineMarker(token, repository);

  if (marker?.includes('"engine": "openpage"')) return repository;

  const head = await readRepositoryHead(token, repository);
  const recoverableLegacyEmptyRepo =
    head === null && repository.description === defaultDescription(input);

  if (recoverableLegacyEmptyRepo) {
    await initializeOpenPageRepository(token, env, repository, input);
    return repository;
  }

  throw new Error(
    `Repository ${repository.full_name} already exists and is not marked as an AppFactory OpenPage project. Choose another slug.`
  );
}

export async function createOpenPageRepository(
  token: string,
  env: Env,
  input: CreateProjectRequest & { slug: string }
): Promise<{ repository: GitHubRepository; created: boolean }> {
  const owner = ownerFromEnv(env);
  const path = `/orgs/${encodeURIComponent(owner)}/repos`;

  try {
    const repository = await githubRequest<GitHubRepository>(token, path, {
      method: "POST",
      body: JSON.stringify({
        name: input.slug,
        description: input.description || defaultDescription(input),
        private: input.private ?? true,
        auto_init: false
      })
    });
    await initializeOpenPageRepository(token, env, repository, input);
    return { repository, created: true };
  } catch (error) {
    if (!(error instanceof GitHubApiError) || error.status !== 422) throw error;
    return {
      repository: await getExistingOpenPageRepository(token, env, owner, input.slug, input),
      created: false
    };
  }
}

function generatedFiles(
  input: CreateProjectRequest & { slug: string },
  config: OpenPageSiteConfig,
  html: string
): Record<string, string> {
  const packageJson = {
    name: input.slug,
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: {
      build: "node scripts/build.mjs",
      typecheck: "node -e \"console.log('OpenPage static export: no TypeScript typecheck required')\""
    }
  };
  const packageLock = {
    name: input.slug,
    version: "0.0.0",
    lockfileVersion: 3,
    requires: true,
    packages: {
      "": {
        name: input.slug,
        version: "0.0.0"
      }
    }
  };

  return {
    [ENGINE_MARKER_PATH]: engineMarkerText(input),
    "openpage.json": `${JSON.stringify(config, null, 2)}\n`,
    "index.html": html.endsWith("\n") ? html : `${html}\n`,
    "package.json": `${JSON.stringify(packageJson, null, 2)}\n`,
    "package-lock.json": `${JSON.stringify(packageLock, null, 2)}\n`,
    "scripts/build.mjs": `import { copyFile, mkdir, rm } from "node:fs/promises";\n\nawait rm("dist", { recursive: true, force: true });\nawait mkdir("dist", { recursive: true });\nawait copyFile("index.html", "dist/index.html");\nconsole.log("OpenPage export copied to dist/index.html");\n`,
    ".github/workflows/ci.yml": `name: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n\njobs:\n  validate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: npm\n      - run: npm ci\n      - run: npm run typecheck\n      - run: npm run build\n`,
    "README.md": `# ${input.name}\n\nGenerated by Trigenys AppFactory using the OpenPage generation engine.\n\n- Engine config: \`openpage.json\`\n- Production artifact: \`dist/index.html\`\n- Build: \`npm run build\`\n`,
    "OPENPAGE-NOTICE.md": `# OpenPage engine notice\n\nThis site was generated with the Trigenys AppFactory OpenPage engine, based on the MIT-licensed OpenPage project by Federico De Ponte.\n\nUpstream: https://github.com/buildingopen/openpage\n\nOpenPage is used as generation/rendering infrastructure; this generated site's business content belongs to the project owner.\n`
  };
}

async function readContentSha(
  token: string,
  repository: GitHubRepository,
  branch: string,
  path: string
): Promise<string | null> {
  const [owner, repo] = repository.full_name.split("/");
  const encodedPath = encodeContentPath(path);

  try {
    const file = await githubRequest<{ sha: string }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${encodedPath}?ref=${encodeURIComponent(branch)}`
    );
    return file.sha;
  } catch (error) {
    if (error instanceof GitHubApiError && error.status === 404) return null;
    throw error;
  }
}

async function upsertGeneratedFile(
  token: string,
  env: Env,
  repository: GitHubRepository,
  branch: string,
  path: string,
  content: string,
  message: string
): Promise<string> {
  const [owner, repo] = repository.full_name.split("/");
  const encodedPath = encodeContentPath(path);
  const sha = await readContentSha(token, repository, branch, path);

  const result = await githubRequest<{ commit: { sha: string } }>(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${encodedPath}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message,
        content: encodeBase64Utf8(content),
        branch,
        author: commitAuthor(env),
        ...(sha ? { sha } : {})
      })
    }
  );

  return result.commit.sha;
}

export async function commitOpenPageSite(
  token: string,
  env: Env,
  repository: GitHubRepository,
  created: boolean,
  input: CreateProjectRequest & { slug: string },
  config: OpenPageSiteConfig,
  html: string
): Promise<string> {
  const branch = repository.default_branch || "main";
  const head = await readRepositoryHead(token, repository);
  if (!head) {
    throw new Error(`Repository ${repository.full_name} was not initialized before OpenPage commit.`);
  }

  const files = generatedFiles(input, config, html);
  let lastCommitSha = head.commitSha;
  let fileIndex = 0;

  for (const [path, content] of Object.entries(files)) {
    fileIndex += 1;
    lastCommitSha = await upsertGeneratedFile(
      token,
      env,
      repository,
      branch,
      path,
      content,
      fileIndex === 1
        ? created
          ? "feat(appfactory): generate OpenPage site"
          : "chore(appfactory): regenerate OpenPage site"
        : `chore(appfactory): sync generated file ${path}`
    );
  }

  return lastCommitSha;
}
