import type {
  CreateProjectRequest,
  Env,
  GitHubRepository,
  WebAppPreset,
  UiProfile
} from "./types";

const GITHUB_API = "https://api.github.com";
const GITHUB_API_VERSION = "2022-11-28";
const BLUEPRINT_VERSION = 1;
const UI_REGISTRY_VERSION = 1;

class GitHubWebAppApiError extends Error {
  constructor(readonly status: number, readonly path: string, detail: string) {
    super(`GitHub API ${status} on ${path}: ${detail}`);
  }
}

interface GitTreeEntry {
  path: string;
  mode: string;
  type: string;
  sha: string;
}

interface WebAppMarker {
  schemaVersion: number;
  projectType: "webapp";
  preset: WebAppPreset;
  blueprintVersion: number;
  uiProfile?: UiProfile;
  uiRegistryVersion?: number;
}

async function githubRequest<T>(token: string, path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": GITHUB_API_VERSION,
      "User-Agent": "Trigenys-AppFactory",
      ...(init.headers || {})
    }
  });

  if (!response.ok) {
    throw new GitHubWebAppApiError(response.status, path, await response.text());
  }

  return (await response.json()) as T;
}

function decodeBase64(value: string): string {
  const binary = atob(value.replace(/\s+/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return new TextDecoder().decode(bytes);
}

function encodeBase64(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

async function fetchRepository(token: string, owner: string, slug: string): Promise<GitHubRepository | null> {
  try {
    return await githubRequest<GitHubRepository>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(slug)}`
    );
  } catch (error) {
    if (error instanceof GitHubWebAppApiError && error.status === 404) return null;
    throw error;
  }
}

async function createRepository(
  token: string,
  owner: string,
  input: CreateProjectRequest & { slug: string }
): Promise<GitHubRepository> {
  return githubRequest<GitHubRepository>(token, `/orgs/${encodeURIComponent(owner)}/repos`, {
    method: "POST",
    body: JSON.stringify({
      name: input.slug,
      description: input.description || `Generated by AppFactory for ${input.name}`,
      private: input.private ?? true,
      auto_init: true,
      has_issues: true,
      has_projects: true,
      has_wiki: false
    })
  });
}

async function readJsonFile<T>(
  token: string,
  repository: GitHubRepository,
  path: string
): Promise<T | null> {
  const [owner, repo] = repository.full_name.split("/");
  try {
    const file = await githubRequest<{ content: string; encoding: string }>(
      token,
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path}`
    );
    if (file.encoding !== "base64") throw new Error(`Unsupported GitHub content encoding for ${path}.`);
    return JSON.parse(decodeBase64(file.content)) as T;
  } catch (error) {
    if (error instanceof GitHubWebAppApiError && error.status === 404) return null;
    throw error;
  }
}

async function writeProvisioningMarker(
  token: string,
  repository: GitHubRepository,
  preset: WebAppPreset,
  uiProfile?: UiProfile
): Promise<void> {
  const [owner, repo] = repository.full_name.split("/");
  const path = ".appfactory/webapp-provisioning.json";
  const body = {
    schemaVersion: 1,
    projectType: "webapp",
    preset,
    blueprintVersion: BLUEPRINT_VERSION,
    ...(uiProfile ? { uiProfile, uiRegistryVersion: UI_REGISTRY_VERSION } : {}),
    complete: false
  };

  await githubRequest(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${path}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message: "chore(appfactory): claim webapp provisioning",
        content: encodeBase64(`${JSON.stringify(body, null, 2)}\n`),
        branch: repository.default_branch || "main"
      })
    }
  );
}

async function getHeadSha(token: string, repository: GitHubRepository): Promise<string> {
  const [owner, repo] = repository.full_name.split("/");
  const ref = await githubRequest<{ object: { sha: string } }>(
    token,
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/ref/heads/${encodeURIComponent(repository.default_branch || "main")}`
  );
  return ref.object.sha;
}

function escapeJsonString(value: string): string {
  return JSON.stringify(value).slice(1, -1);
}

function renderBlueprintText(
  content: string,
  context: { owner: string; name: string; slug: string }
): string {
  return content
    .replaceAll("__OWNER__", context.owner)
    .replaceAll("__APP_NAME_JSON__", escapeJsonString(context.name))
    .replaceAll("__APP_NAME__", context.name)
    .replaceAll("__APP_SLUG__", context.slug);
}

async function materializeBlueprint(
  token: string,
  env: Env,
  repository: GitHubRepository,
  preset: WebAppPreset,
  appName: string,
  uiProfile?: UiProfile
): Promise<string> {
  const targetOwner = env.GITHUB_OWNER || "Trigenys";
  const sourceOwner = env.GITHUB_WEBAPP_BLUEPRINT_OWNER || targetOwner;
  const sourceRepo = env.GITHUB_WEBAPP_BLUEPRINT_REPO || "appfactory";
  const source = await githubRequest<GitHubRepository>(
    token,
    `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}`
  );
  const sourceRef = env.GITHUB_WEBAPP_BLUEPRINT_REF || source.default_branch || "main";
  const prefix = `blueprints/${preset}/`;
  const tree = await githubRequest<{ truncated: boolean; tree: GitTreeEntry[] }>(
    token,
    `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}/git/trees/${encodeURIComponent(sourceRef)}?recursive=1`
  );
  if (tree.truncated) throw new Error("AppFactory webapp blueprint tree is too large to materialize safely.");

  const sourceBlobs = tree.tree.filter((entry) => entry.type === "blob" && entry.path.startsWith(prefix));
  if (sourceBlobs.length === 0) throw new Error(`No files found for webapp blueprint ${preset}.`);

  // The default blueprint remains unchanged; add owned UI components only when selected.
  const profileExtras: Array<{ sourcePath: string; targetPath: string }> = uiProfile ? [
    { sourcePath: "ui-registry/templates/ProfileApp.tsx", targetPath: "src/App.tsx" },
    { sourcePath: "ui-registry/templates/ProfileStyles.css", targetPath: "src/styles.css" },
    { sourcePath: "ui-registry/components/UiButton.tsx", targetPath: "src/components/ui/UiButton.tsx" },
    { sourcePath: "ui-registry/components/UiCard.tsx", targetPath: "src/components/ui/UiCard.tsx" },
    { sourcePath: "ui-registry/components/WhatsAppCta.tsx", targetPath: "src/components/ui/WhatsAppCta.tsx" },
    { sourcePath: "ui-registry/components/ui.css", targetPath: "src/components/ui/ui.css" }
  ] : [];
  let tokens: Record<string, string> = {};
  if (uiProfile) {
    const config = tree.tree.find((entry) => entry.type === "blob" && entry.path === "ui-registry/profiles.json");
    if (!config) throw new Error("UI profile catalog is missing from the AppFactory source.");
    const source = await githubRequest<{ content: string; encoding: string }>(
      token, `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}/git/blobs/${config.sha}`
    );
    if (source.encoding !== "base64") throw new Error("Unsupported UI profile catalog encoding.");
    const catalog = JSON.parse(decodeBase64(source.content)) as {
      version: number;
      profiles: Record<string, { tokens: Record<string, string> }>;
    };
    if (catalog.version !== UI_REGISTRY_VERSION || !catalog.profiles[uiProfile]) {
      throw new Error(`Unsupported UI registry version or profile: ${uiProfile}.`);
    }
    tokens = catalog.profiles[uiProfile].tokens;
    if (!["bg", "surface", "text", "muted", "accent", "border", "radius"].every((key) => !!tokens[key])) {
      throw new Error(`Incomplete tokens for UI profile ${uiProfile}.`);
    }
  }
  const mappedFiles = [
    ...sourceBlobs.map((entry) => ({ entry, targetPath: entry.path.slice(prefix.length) })),
    ...profileExtras.map(({ sourcePath, targetPath }) => {
      const entry = tree.tree.find((item) => item.type === "blob" && item.path === sourcePath);
      if (!entry) throw new Error(`Required UI Registry source missing: ${sourcePath}.`);
      return { entry, targetPath };
    })
  ];

  const [, targetRepo] = repository.full_name.split("/");
  const binaryExtensions = [".ico", ".png", ".jpg", ".jpeg", ".webp", ".woff", ".woff2"];

  const targetEntries = await Promise.all(mappedFiles.map(async ({ entry, targetPath }) => {
    const sourceBlob = await githubRequest<{ content: string; encoding: string }>(
      token,
      `/repos/${encodeURIComponent(sourceOwner)}/${encodeURIComponent(sourceRepo)}/git/blobs/${entry.sha}`
    );
    if (sourceBlob.encoding !== "base64") throw new Error(`Unsupported blueprint encoding for ${entry.path}.`);

    const isBinary = binaryExtensions.some((extension) => entry.path.toLowerCase().endsWith(extension));
    let rendered = isBinary ? "" : renderBlueprintText(decodeBase64(sourceBlob.content), {
      owner: targetOwner,
      name: appName,
      slug: repository.name
    });
    if (uiProfile && targetPath === "src/styles.css") {
      for (const [key, value] of Object.entries(tokens)) {
        rendered = rendered.replaceAll(`__UI_${key.toUpperCase()}__`, value);
      }
      if (/__UI_[A-Z_]+__/.test(rendered)) throw new Error("Unresolved UI profile token.");
    }
    if (uiProfile && targetPath === ".appfactory/webapp.json") {
      const marker = JSON.parse(rendered) as WebAppMarker;
      rendered = `${JSON.stringify({ ...marker, uiProfile, uiRegistryVersion: UI_REGISTRY_VERSION }, null, 2)}\n`;
    }
    const content = isBinary ? sourceBlob.content.replace(/\s+/g, "") : encodeBase64(rendered);

    const targetBlob = await githubRequest<{ sha: string }>(
      token,
      `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/blobs`,
      {
        method: "POST",
        body: JSON.stringify({ content, encoding: "base64" })
      }
    );

    return {
      path: targetPath,
      mode: entry.mode,
      type: "blob",
      sha: targetBlob.sha
    };
  }));

  const targetTree = await githubRequest<{ sha: string }>(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/trees`,
    { method: "POST", body: JSON.stringify({ tree: [...new Map(targetEntries.map((entry) => [entry.path, entry])).values()] }) }
  );
  const parentSha = await getHeadSha(token, repository);
  const commit = await githubRequest<{ sha: string }>(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/commits`,
    {
      method: "POST",
      body: JSON.stringify({
        message: `feat(appfactory): materialize ${preset} webapp blueprint`,
        tree: targetTree.sha,
        parents: [parentSha]
      })
    }
  );
  await githubRequest(
    token,
    `/repos/${encodeURIComponent(targetOwner)}/${encodeURIComponent(targetRepo)}/git/refs/heads/${encodeURIComponent(repository.default_branch || "main")}`,
    { method: "PATCH", body: JSON.stringify({ sha: commit.sha, force: false }) }
  );
  return commit.sha;
}

function markerMatches(marker: WebAppMarker | null, preset: WebAppPreset): marker is WebAppMarker {
  return Boolean(
    marker &&
    marker.schemaVersion === 1 &&
    marker.projectType === "webapp" &&
    marker.preset === preset
  );
}

export async function provisionWebAppRepository(
  token: string,
  env: Env,
  input: CreateProjectRequest & {
    slug: string;
    projectType: "webapp";
    preset: WebAppPreset;
  }
): Promise<{
  repository: GitHubRepository;
  commitSha: string;
  replay: boolean;
  blueprintVersion: number;
}> {
  const owner = env.GITHUB_OWNER || "Trigenys";
  let repository = await fetchRepository(token, owner, input.slug);

  if (repository) {
    const marker = await readJsonFile<WebAppMarker>(token, repository, ".appfactory/webapp.json");
    if (markerMatches(marker, input.preset)) {
      if (marker.uiProfile !== input.uiProfile) {
        throw new Error(`Repository ${repository.full_name} already has UI profile ${marker.uiProfile || "none"}; refusing to overwrite it with ${input.uiProfile || "none"}.`);
      }
      if (input.uiProfile && marker.uiRegistryVersion !== UI_REGISTRY_VERSION) {
        throw new Error(`Repository ${repository.full_name} uses a different UI registry version; upgrade required.`);
      }
      if (marker.blueprintVersion === BLUEPRINT_VERSION) {
        return {
          repository,
          commitSha: await getHeadSha(token, repository),
          replay: true,
          blueprintVersion: BLUEPRINT_VERSION
        };
      }
      throw new Error(
        `Repository ${repository.full_name} uses webapp blueprint version ${marker.blueprintVersion}; no managed upgrade path exists to v${BLUEPRINT_VERSION}.`
      );
    }

    const provisioning = await readJsonFile<WebAppMarker & { complete?: boolean }>(
      token,
      repository,
      ".appfactory/webapp-provisioning.json"
    );
    if (!provisioning || provisioning.preset !== input.preset || provisioning.complete !== false || provisioning.uiProfile !== input.uiProfile) {
      throw new Error(
        `Repository ${repository.full_name} already exists and is not managed by the requested webapp preset.`
      );
    }
  } else {
    repository = await createRepository(token, owner, input);
    await writeProvisioningMarker(token, repository, input.preset, input.uiProfile);
  }

  const commitSha = await materializeBlueprint(token, env, repository, input.preset, input.name, input.uiProfile);
  return {
    repository,
    commitSha,
    replay: false,
    blueprintVersion: BLUEPRINT_VERSION
  };
}
